      - name: Build Xcode Compile
        run: |
          xcodebuild -workspace YourProject.xcworkspace \
            -scheme YourScheme \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO

      - name: Package to IPA Manual
        run: |
          # 1. Buat folder Payload
          mkdir -p Payload
          
          # 2. Cari file .app di dalam folder build yang sudah kita tentukan
          # Lalu copy ke dalam folder Payload
          find build/Build/Products/Release-iphoneos -name "*.app" -exec cp -r {} Payload/ \;
          
          # 3. Zip menjadi .ipa
          zip -r YourAppName.ipa Payload
          
          echo "Packaging selesai!"

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-bundle
          path: HELL SENSX.ipa
